# Generated by Django 4.1.7 on 2023-03-30 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_qualification_programs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.contact')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.programs')),
            ],
        ),
    ]
