# Generated by Django 4.1.7 on 2023-04-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_application_email_application_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
