# Generated by Django 4.1.7 on 2023-04-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_school_department_programs_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
