# Generated by Django 4.1.7 on 2023-04-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_rename_is_approved_application_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='qualification',
        ),
        migrations.AddField(
            model_name='programs',
            name='qualification',
            field=models.ManyToManyField(to='Application.qualification'),
        ),
    ]
