# Generated by Django 4.1.7 on 2023-04-16 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_remove_programs_qualification_programs_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='qualification',
        ),
        migrations.AddField(
            model_name='programs',
            name='qualification',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Application.qualification'),
            preserve_default=False,
        ),
    ]
