# Generated by Django 4.1.7 on 2023-04-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_remove_programs_qualification_programs_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='program',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Programs',
        ),
    ]
