# Generated by Django 4.1.7 on 2023-04-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_programs_alter_application_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='approved',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
